## Lab 10 ##

In [122]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import image_dataset_from_directory
import pathlib
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
# installed pandas in this venv
import pandas as pd

I want to keep the only the 3 classes with the highest number of images. This information can be found in the attached birds.csv in the dataset.

In [2]:
metadata_df = pd.read_csv('/Users/karlokng/Downloads/data/birds_525/birds.csv')
print(metadata_df['class id'].value_counts().head(3))
print(metadata_df['labels'].value_counts().head(3))

class id
426.0    273
286.0    258
181.0    243
Name: count, dtype: int64
labels
RUFOUS TREPE        273
HOUSE FINCH         258
D-ARNAUDS BARBET    243
Name: count, dtype: int64


We see that the class with id 426, 286 and 181 are the classes with the highest number of photos.
These 3 class IDs correspond to the labels RUFOUS TREPE, HOUSE FINCH and D-ARNAUDS BARBET. As such, we'll keep these 3 folders in the data set, and drop everything else.

We note that the classes are relatively balanced, with the least (D_ARNAUDS BARBET) having 30 fewer images than the most (RUFOUS TREPE).

This was done manually using the system's file explorer.

The rest of the code is adapted from the in class 05C and 05D notebooks. Any changes would be pointed out in comments.

In [4]:
# define a function to augment data
data_augmentation = keras.Sequential(
    [
        layers.RandomFlip("horizontal"),
        layers.RandomRotation(0.2), # changed the percentages a little
        layers.RandomZoom(0.3),
        layers.RandomTranslation(height_factor=(-0.2, 0.2),
                                 width_factor=(-0.2, 0.2)) # translates images left/right/up/down
    ]
)

In [6]:
data_folder = pathlib.Path('/Users/karlokng/Downloads/data/birds_525')

train_dataset = image_dataset_from_directory(
    data_folder / "train",
    image_size=(224, 224), # image_size is changed to the image size of the data
    batch_size=32)
validation_dataset = image_dataset_from_directory(
    data_folder / "valid",
    image_size=(224, 224),
    batch_size=32)
test_dataset = image_dataset_from_directory(
    data_folder / "test",
    image_size=(224, 224),
    batch_size=32)

Found 744 files belonging to 3 classes.
Found 15 files belonging to 3 classes.
Found 15 files belonging to 3 classes.


In [8]:
import numpy as np

conv_base = keras.applications.vgg16.VGG16(
    weights="imagenet",
    include_top=False,
    input_shape=(224, 224, 3)) # input_shape change to accomodate change in image size
conv_base.trainable = False

def get_features_and_labels(dataset):
    all_features = []
    all_labels = []
    for images, labels in dataset:
        preprocessed_images = keras.applications.vgg16.preprocess_input(images)
        features = conv_base.predict(preprocessed_images)
        all_features.append(features)
        all_labels.append(labels)
    return np.concatenate(all_features), np.concatenate(all_labels)

train_features, train_labels =  get_features_and_labels(train_dataset)
val_features, val_labels =  get_features_and_labels(validation_dataset)
test_features, test_labels =  get_features_and_labels(test_dataset)

1/1 [==============================] - 0s 245ms/step


2023-12-02 16:27:07.156966: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 19ms/step


In [12]:
train_features.shape # double check features shape

(744, 7, 7, 512)

In [147]:
# define the dense layers at the end
inputs = keras.Input(shape=(224, 224, 3)) # change input shape to reflect train_dataset
x = data_augmentation(inputs)
x = keras.applications.vgg16.preprocess_input(x)
x = conv_base(x)
x = layers.Flatten()(x)

# adding 3 layers of Dense nodes, emulating the original structure of VGG16
x = layers.Dense(4096)(x)
x = layers.Dense(4096)(x)
x = layers.Dense(1000)(x)
x = layers.Dropout(0.5)(x)

# change output layers to 3 as we have 3 classes
# activation = "softmax" as we are working with 3 classes as well
outputs = layers.Dense(3, activation="softmax")(x)
model = keras.Model(inputs, outputs)

model.summary()

Model: "model_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_15 (InputLayer)       [(None, 224, 224, 3)]     0         
                                                                 
 sequential_1 (Sequential)   (None, None, None, None   0         
                             )                                   
                                                                 
 tf.__operators__.getitem_7  (None, 224, 224, 3)       0         
  (SlicingOpLambda)                                              
                                                                 
 tf.nn.bias_add_7 (TFOpLamb  (None, 224, 224, 3)       0         
 da)                                                             
                                                                 
 vgg16 (Functional)          (None, 7, 7, 512)         14714688  
                                                           

In [27]:
set(train_labels) # we see that our labels are not one-hot encoded

{0, 1, 2}

Since our labels are not one-hot encoded, we would use sparse_categorical_crossentropy.

In [148]:
model.compile(loss="sparse_categorical_crossentropy",
              optimizer="rmsprop",
              metrics=["accuracy"])

callbacks = [
    keras.callbacks.ModelCheckpoint(
      filepath="./models/vgg16_bird_classifier.tf",
      save_best_only=True,
      monitor="val_loss")
]
history = model.fit(
    train_dataset,
    epochs=20,
    validation_data= validation_dataset,
    callbacks=callbacks)

Epoch 1/20


2023-12-02 22:00:23.084081: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 1:07 - loss: 27.8413 - accuracy: 0.3438

2023-12-02 22:00:25.044302: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 15s - loss: 2605.4153 - accuracy: 0.3281

2023-12-02 22:00:25.779203: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 15s - loss: 12094.4385 - accuracy: 0.4062

2023-12-02 22:00:26.485774: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 14s - loss: 227016.0781 - accuracy: 0.3750

2023-12-02 22:00:27.192436: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 13s - loss: 203059.3750 - accuracy: 0.3750

2023-12-02 22:00:27.899640: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 177681.3125 - accuracy: 0.3750

2023-12-02 22:00:28.631235: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 12s - loss: 161171.1719 - accuracy: 0.3661

2023-12-02 22:00:29.371277: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 11s - loss: 143522.5156 - accuracy: 0.3750

2023-12-02 22:00:30.092514: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 128387.5391 - accuracy: 0.3854

2023-12-02 22:00:30.828152: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 10s - loss: 115867.1641 - accuracy: 0.3969

2023-12-02 22:00:31.581234: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 9s - loss: 105499.8672 - accuracy: 0.4347 

2023-12-02 22:00:32.321457: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 96769.0547 - accuracy: 0.4766 

2023-12-02 22:00:33.030281: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 89417.9062 - accuracy: 0.5024

2023-12-02 22:00:33.716313: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 7s - loss: 83093.0234 - accuracy: 0.5290

2023-12-02 22:00:34.397657: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 77562.8594 - accuracy: 0.5583

2023-12-02 22:00:35.081340: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 72737.4141 - accuracy: 0.5801

2023-12-02 22:00:35.752079: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 68470.8281 - accuracy: 0.5974

2023-12-02 22:00:36.417200: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 64717.7969 - accuracy: 0.6111

2023-12-02 22:00:37.115836: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 61317.3672 - accuracy: 0.6283

2023-12-02 22:00:37.863620: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 58281.6680 - accuracy: 0.6438

2023-12-02 22:00:38.571109: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 55517.6719 - accuracy: 0.6592

2023-12-02 22:00:39.265033: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 52998.2617 - accuracy: 0.6733

2023-12-02 22:00:40.009114: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 50703.2773 - accuracy: 0.6848

2023-12-02 22:00:40.760165: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - ETA: 0s - loss: 50158.0820 - accuracy: 0.6882INFO:tensorflow:Assets written to: ./models/vgg16_bird_classifier.tf/assets


INFO:tensorflow:Assets written to: ./models/vgg16_bird_classifier.tf/assets


24/24 [==============================] - 25s 975ms/step - loss: 50158.0820 - accuracy: 0.6882 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 2/20


2023-12-02 22:00:47.489001: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 21s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:00:48.424591: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 139.3115 - accuracy: 0.9844  

2023-12-02 22:00:49.099494: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 16s - loss: 192.0615 - accuracy: 0.9688

2023-12-02 22:00:49.962222: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 15s - loss: 167.4683 - accuracy: 0.9688

2023-12-02 22:00:50.678224: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 14s - loss: 133.9746 - accuracy: 0.9750

2023-12-02 22:00:51.388890: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 13s - loss: 111.6455 - accuracy: 0.9792

2023-12-02 22:00:52.115913: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 12s - loss: 95.6962 - accuracy: 0.9821 

2023-12-02 22:00:52.890898: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 11s - loss: 100.3680 - accuracy: 0.9805

2023-12-02 22:00:53.599415: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 11s - loss: 130.8035 - accuracy: 0.9757

2023-12-02 22:00:54.293099: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 10s - loss: 128.4748 - accuracy: 0.9688

2023-12-02 22:00:54.967063: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 9s - loss: 120.0231 - accuracy: 0.9688 

2023-12-02 22:00:55.663262: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 110.0212 - accuracy: 0.9714

2023-12-02 22:00:56.360937: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 138.8963 - accuracy: 0.9663

2023-12-02 22:00:57.059864: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 7s - loss: 151.3648 - accuracy: 0.9643

2023-12-02 22:00:57.731586: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 141.2738 - accuracy: 0.9667

2023-12-02 22:00:58.402407: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 137.3501 - accuracy: 0.9648

2023-12-02 22:00:59.080034: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 143.7392 - accuracy: 0.9632

2023-12-02 22:00:59.799884: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 137.9308 - accuracy: 0.9618

2023-12-02 22:01:00.480482: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 131.1120 - accuracy: 0.9622

2023-12-02 22:01:01.151428: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 143.6845 - accuracy: 0.9594

2023-12-02 22:01:01.829399: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 167.0325 - accuracy: 0.9494

2023-12-02 22:01:02.516351: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 159.9632 - accuracy: 0.9489

2023-12-02 22:01:03.265550: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 154.9973 - accuracy: 0.9497

2023-12-02 22:01:03.971474: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 17s 708ms/step - loss: 153.3307 - accuracy: 0.9503 - val_loss: 155.9860 - val_accuracy: 0.9333
Epoch 3/20


2023-12-02 22:01:04.707853: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 17s - loss: 1114.1797 - accuracy: 0.7188

2023-12-02 22:01:05.457405: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 5035.4727 - accuracy: 0.5938

2023-12-02 22:01:06.147483: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 3492.2937 - accuracy: 0.7083

2023-12-02 22:01:06.847262: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 2807.5571 - accuracy: 0.7422

2023-12-02 22:01:07.543000: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 13s - loss: 3442.0508 - accuracy: 0.7063

2023-12-02 22:01:08.226220: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 8029.1079 - accuracy: 0.6562

2023-12-02 22:01:08.913678: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 7981.5000 - accuracy: 0.6562

2023-12-02 22:01:09.605444: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 11s - loss: 11334.7148 - accuracy: 0.6172

2023-12-02 22:01:10.312512: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 13683.6064 - accuracy: 0.6076

2023-12-02 22:01:10.987465: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 21064.2754 - accuracy: 0.5938 

2023-12-02 22:01:11.670402: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 21344.4453 - accuracy: 0.5909

2023-12-02 22:01:12.370834: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 23822.1641 - accuracy: 0.5755

2023-12-02 22:01:13.048470: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 21993.8555 - accuracy: 0.6058

2023-12-02 22:01:13.732000: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 20478.4668 - accuracy: 0.6272

2023-12-02 22:01:14.403461: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 19205.1816 - accuracy: 0.6479

2023-12-02 22:01:15.080651: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 18012.6191 - accuracy: 0.6660

2023-12-02 22:01:15.760132: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 16970.4355 - accuracy: 0.6820

2023-12-02 22:01:16.424825: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 16051.0889 - accuracy: 0.6979

2023-12-02 22:01:17.094493: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 15207.3057 - accuracy: 0.7122

2023-12-02 22:01:17.774477: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 14447.9688 - accuracy: 0.7250

2023-12-02 22:01:18.442682: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 13764.6982 - accuracy: 0.7366

2023-12-02 22:01:19.121303: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 13139.0303 - accuracy: 0.7486

2023-12-02 22:01:19.795404: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 12567.7676 - accuracy: 0.7595

2023-12-02 22:01:20.473184: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 17s 692ms/step - loss: 12432.6309 - accuracy: 0.7621 - val_loss: 721.8035 - val_accuracy: 0.9333
Epoch 4/20


2023-12-02 22:01:21.361239: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 787.0627 - accuracy: 0.9375

2023-12-02 22:01:22.098135: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 404.7249 - accuracy: 0.9531

2023-12-02 22:01:22.772662: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 269.8166 - accuracy: 0.9688

2023-12-02 22:01:23.456740: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 202.3624 - accuracy: 0.9766

2023-12-02 22:01:24.123390: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 12s - loss: 185.1981 - accuracy: 0.9750

2023-12-02 22:01:24.785225: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 154.3318 - accuracy: 0.9792

2023-12-02 22:01:25.449286: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 132.2844 - accuracy: 0.9821

2023-12-02 22:01:26.134205: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 117.6615 - accuracy: 0.9805

2023-12-02 22:01:26.799475: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 196.1891 - accuracy: 0.9757

2023-12-02 22:01:27.478607: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 176.5702 - accuracy: 0.9781 

2023-12-02 22:01:28.147327: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 172.3416 - accuracy: 0.9773

2023-12-02 22:01:28.815548: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 165.0870 - accuracy: 0.9766

2023-12-02 22:01:29.496921: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 157.0430 - accuracy: 0.9760

2023-12-02 22:01:30.171753: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 145.8256 - accuracy: 0.9777

2023-12-02 22:01:30.842044: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 136.1039 - accuracy: 0.9792

2023-12-02 22:01:31.586307: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 152.6231 - accuracy: 0.9746

2023-12-02 22:01:32.348253: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 143.6453 - accuracy: 0.9761

2023-12-02 22:01:33.052641: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 135.6650 - accuracy: 0.9774

2023-12-02 22:01:33.736639: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 154.6768 - accuracy: 0.9770

2023-12-02 22:01:34.413199: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 183.1993 - accuracy: 0.9734

2023-12-02 22:01:35.081829: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 182.9488 - accuracy: 0.9732

2023-12-02 22:01:35.747564: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 247.2797 - accuracy: 0.9688

2023-12-02 22:01:36.425126: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 298.4050 - accuracy: 0.9620

2023-12-02 22:01:37.099291: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 17s 687ms/step - loss: 309.4456 - accuracy: 0.9610 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 5/20


2023-12-02 22:01:37.890228: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 17s - loss: 416.6741 - accuracy: 0.9375

2023-12-02 22:01:38.679525: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 15s - loss: 265.8376 - accuracy: 0.9531

2023-12-02 22:01:39.360057: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 317.5882 - accuracy: 0.9583

2023-12-02 22:01:40.025686: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 1078.2766 - accuracy: 0.9297

2023-12-02 22:01:40.758117: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 13s - loss: 917.7833 - accuracy: 0.9375 

2023-12-02 22:01:41.620215: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 13s - loss: 1197.1791 - accuracy: 0.9271

2023-12-02 22:01:42.405750: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 12s - loss: 1034.0662 - accuracy: 0.9286

2023-12-02 22:01:43.166096: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 11s - loss: 964.6518 - accuracy: 0.9258 

2023-12-02 22:01:43.892131: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 11s - loss: 957.1271 - accuracy: 0.9167

2023-12-02 22:01:44.635211: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 10s - loss: 944.1172 - accuracy: 0.9062

2023-12-02 22:01:45.337025: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 9s - loss: 871.0239 - accuracy: 0.9119 

2023-12-02 22:01:46.092030: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 898.3996 - accuracy: 0.9089

2023-12-02 22:01:46.817061: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 8s - loss: 909.8895 - accuracy: 0.9087

2023-12-02 22:01:47.511943: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 7s - loss: 844.8974 - accuracy: 0.9152

2023-12-02 22:01:48.181428: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 788.5709 - accuracy: 0.9208

2023-12-02 22:01:48.849197: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 745.6373 - accuracy: 0.9238

2023-12-02 22:01:49.520149: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 5s - loss: 765.4297 - accuracy: 0.9228

2023-12-02 22:01:50.195441: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 832.8101 - accuracy: 0.9201

2023-12-02 22:01:50.866670: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 788.9780 - accuracy: 0.9243

2023-12-02 22:01:51.583648: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 823.5980 - accuracy: 0.9234

2023-12-02 22:01:52.293363: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 935.3915 - accuracy: 0.9092

2023-12-02 22:01:52.958378: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 1812.5724 - accuracy: 0.8878

2023-12-02 22:01:53.656824: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 2075.1006 - accuracy: 0.8777

2023-12-02 22:01:54.348127: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 17s 713ms/step - loss: 2213.2869 - accuracy: 0.8723 - val_loss: 49456.5078 - val_accuracy: 0.6667
Epoch 6/20


2023-12-02 22:01:55.083014: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 18s - loss: 31978.9395 - accuracy: 0.6250

2023-12-02 22:01:55.878005: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 23788.3320 - accuracy: 0.6719

2023-12-02 22:01:56.550089: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 17728.0742 - accuracy: 0.6979

2023-12-02 22:01:57.271463: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 14212.5273 - accuracy: 0.7266

2023-12-02 22:01:57.961393: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 13s - loss: 11424.4316 - accuracy: 0.7750

2023-12-02 22:01:58.636323: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 9696.3770 - accuracy: 0.8073 

2023-12-02 22:01:59.385394: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 12s - loss: 8356.4473 - accuracy: 0.8304

2023-12-02 22:02:00.153667: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 11s - loss: 7533.8267 - accuracy: 0.8477

2023-12-02 22:02:00.851626: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 6696.7349 - accuracy: 0.8646

2023-12-02 22:02:01.521986: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 6153.6641 - accuracy: 0.8719 

2023-12-02 22:02:02.199076: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 9s - loss: 5594.2402 - accuracy: 0.8835

2023-12-02 22:02:02.926425: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 5128.0532 - accuracy: 0.8932

2023-12-02 22:02:03.664500: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 4733.5879 - accuracy: 0.9014

2023-12-02 22:02:04.431518: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 7s - loss: 4464.4448 - accuracy: 0.9062

2023-12-02 22:02:05.158766: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 4166.8149 - accuracy: 0.9125

2023-12-02 22:02:05.841108: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 3912.7937 - accuracy: 0.9160

2023-12-02 22:02:06.513845: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 3716.0486 - accuracy: 0.9191

2023-12-02 22:02:07.225363: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 3509.8142 - accuracy: 0.9219

2023-12-02 22:02:07.932567: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 3334.3926 - accuracy: 0.9243

2023-12-02 22:02:08.659559: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 3190.9641 - accuracy: 0.9266

2023-12-02 22:02:09.358535: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 3120.7441 - accuracy: 0.9286

2023-12-02 22:02:10.027404: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 3490.4885 - accuracy: 0.9219

2023-12-02 22:02:10.710725: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 3564.9897 - accuracy: 0.9171

2023-12-02 22:02:11.441509: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 17s 709ms/step - loss: 3601.9771 - accuracy: 0.9153 - val_loss: 11467.2852 - val_accuracy: 0.8000
Epoch 7/20


2023-12-02 22:02:12.181681: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 17s - loss: 5743.3052 - accuracy: 0.8125

2023-12-02 22:02:12.937191: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 4030.9146 - accuracy: 0.8750

2023-12-02 22:02:13.615401: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 2687.2764 - accuracy: 0.9167

2023-12-02 22:02:14.327399: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 2234.4497 - accuracy: 0.9297

2023-12-02 22:02:15.005058: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 13s - loss: 2034.2233 - accuracy: 0.9375

2023-12-02 22:02:15.690556: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 2001.5150 - accuracy: 0.9427

2023-12-02 22:02:16.373897: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 1715.5842 - accuracy: 0.9509

2023-12-02 22:02:17.126684: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 11s - loss: 1501.1362 - accuracy: 0.9570

2023-12-02 22:02:17.816730: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 1334.3433 - accuracy: 0.9618

2023-12-02 22:02:18.491775: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 1200.9089 - accuracy: 0.9656 

2023-12-02 22:02:19.165066: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 1127.5547 - accuracy: 0.9659

2023-12-02 22:02:19.850587: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 1033.5918 - accuracy: 0.9688

2023-12-02 22:02:20.523693: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 954.0847 - accuracy: 0.9712 

2023-12-02 22:02:21.194970: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 966.4214 - accuracy: 0.9710

2023-12-02 22:02:21.865248: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 1115.5529 - accuracy: 0.9667

2023-12-02 22:02:22.544844: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 1045.8308 - accuracy: 0.9688

2023-12-02 22:02:23.217901: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 1126.0752 - accuracy: 0.9669

2023-12-02 22:02:23.889104: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 1126.6603 - accuracy: 0.9653

2023-12-02 22:02:24.567782: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 1132.3430 - accuracy: 0.9655

2023-12-02 22:02:25.244059: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 1075.7258 - accuracy: 0.9672

2023-12-02 22:02:25.932259: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 1053.4199 - accuracy: 0.9673

2023-12-02 22:02:26.587550: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 1016.2823 - accuracy: 0.9673

2023-12-02 22:02:27.259605: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 1020.3945 - accuracy: 0.9674

2023-12-02 22:02:27.928286: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 680ms/step - loss: 1009.4225 - accuracy: 0.9677 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 8/20


2023-12-02 22:02:28.583896: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 3896.1528 - accuracy: 0.9062

2023-12-02 22:02:29.309557: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 15s - loss: 1948.0764 - accuracy: 0.9531

2023-12-02 22:02:30.008896: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 1298.7177 - accuracy: 0.9688

2023-12-02 22:02:30.693417: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 1062.8806 - accuracy: 0.9688

2023-12-02 22:02:31.408733: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 13s - loss: 936.8857 - accuracy: 0.9688 

2023-12-02 22:02:32.067687: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 780.7381 - accuracy: 0.9740

2023-12-02 22:02:32.739466: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 669.2041 - accuracy: 0.9777

2023-12-02 22:02:33.408488: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 722.2809 - accuracy: 0.9727

2023-12-02 22:02:34.080279: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 1581.7841 - accuracy: 0.9479

2023-12-02 22:02:34.750477: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 2148.0254 - accuracy: 0.9375 

2023-12-02 22:02:35.418262: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 4189.3931 - accuracy: 0.9176

2023-12-02 22:02:36.095379: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 5085.4814 - accuracy: 0.8958

2023-12-02 22:02:36.807238: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 5893.6338 - accuracy: 0.8846

2023-12-02 22:02:37.484628: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 5974.1094 - accuracy: 0.8750

2023-12-02 22:02:38.174099: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 5575.8354 - accuracy: 0.8833

2023-12-02 22:02:38.847461: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 5448.8950 - accuracy: 0.8848

2023-12-02 22:02:39.517094: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 5262.2285 - accuracy: 0.8879

2023-12-02 22:02:40.185645: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 5126.1475 - accuracy: 0.8924

2023-12-02 22:02:40.862371: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 4856.3501 - accuracy: 0.8980

2023-12-02 22:02:41.527601: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 4613.5327 - accuracy: 0.9031

2023-12-02 22:02:42.198331: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 4393.8408 - accuracy: 0.9077

2023-12-02 22:02:42.872321: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 4194.1206 - accuracy: 0.9119

2023-12-02 22:02:43.567008: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 4045.0515 - accuracy: 0.9144

2023-12-02 22:02:44.245704: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 680ms/step - loss: 4001.5564 - accuracy: 0.9153 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 9/20


2023-12-02 22:02:44.941501: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 175.5337 - accuracy: 0.9375

2023-12-02 22:02:45.677201: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 15s - loss: 157.1826 - accuracy: 0.9531

2023-12-02 22:02:46.362368: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 104.7884 - accuracy: 0.9688

2023-12-02 22:02:47.032469: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 116.0591 - accuracy: 0.9688

2023-12-02 22:02:47.711696: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 12s - loss: 92.8473 - accuracy: 0.9750 

2023-12-02 22:02:48.382836: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 320.1754 - accuracy: 0.9688

2023-12-02 22:02:49.062013: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 318.5477 - accuracy: 0.9643

2023-12-02 22:02:49.737253: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 374.7990 - accuracy: 0.9648

2023-12-02 22:02:50.409833: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 357.7292 - accuracy: 0.9653

2023-12-02 22:02:51.079644: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 321.9563 - accuracy: 0.9688 

2023-12-02 22:02:51.756930: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 445.3748 - accuracy: 0.9631

2023-12-02 22:02:52.426799: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 408.2603 - accuracy: 0.9661

2023-12-02 22:02:53.103627: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 396.8709 - accuracy: 0.9663

2023-12-02 22:02:53.776211: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 373.0558 - accuracy: 0.9665

2023-12-02 22:02:54.445628: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 348.1855 - accuracy: 0.9688

2023-12-02 22:02:55.113050: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 326.4239 - accuracy: 0.9707

2023-12-02 22:02:55.812857: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 307.2224 - accuracy: 0.9724

2023-12-02 22:02:56.485498: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 292.5002 - accuracy: 0.9722

2023-12-02 22:02:57.155528: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 277.1054 - accuracy: 0.9737

2023-12-02 22:02:57.825228: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 263.2502 - accuracy: 0.9750

2023-12-02 22:02:58.494345: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 250.7144 - accuracy: 0.9762

2023-12-02 22:02:59.164015: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 281.2146 - accuracy: 0.9759

2023-12-02 22:02:59.834790: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 268.9879 - accuracy: 0.9769

2023-12-02 22:03:00.505544: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 674ms/step - loss: 266.0956 - accuracy: 0.9772 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 10/20


2023-12-02 22:03:01.180155: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:03:01.912140: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:03:02.583793: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:03:03.253668: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:03:03.922322: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 12s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:03:04.591104: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 74.2981 - accuracy: 0.9948   

2023-12-02 22:03:05.263014: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 63.6841 - accuracy: 0.9955

2023-12-02 22:03:05.934597: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 61.4288 - accuracy: 0.9922

2023-12-02 22:03:06.605009: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 57.3067 - accuracy: 0.9896

2023-12-02 22:03:07.275271: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 51.5761 - accuracy: 0.9906 

2023-12-02 22:03:07.945112: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 322.3986 - accuracy: 0.9858

2023-12-02 22:03:08.618842: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 392.1740 - accuracy: 0.9792

2023-12-02 22:03:09.291075: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 362.0068 - accuracy: 0.9808

2023-12-02 22:03:09.958810: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 336.1491 - accuracy: 0.9821

2023-12-02 22:03:10.627588: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 347.2204 - accuracy: 0.9812

2023-12-02 22:03:11.296034: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 365.7224 - accuracy: 0.9785

2023-12-02 22:03:11.965468: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 383.9115 - accuracy: 0.9743

2023-12-02 22:03:12.640536: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 391.9025 - accuracy: 0.9740

2023-12-02 22:03:13.322951: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 395.8441 - accuracy: 0.9737

2023-12-02 22:03:13.988902: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 382.2911 - accuracy: 0.9734

2023-12-02 22:03:14.657143: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 407.6801 - accuracy: 0.9732

2023-12-02 22:03:15.327906: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 389.1492 - accuracy: 0.9744

2023-12-02 22:03:15.997731: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 372.2297 - accuracy: 0.9755

2023-12-02 22:03:16.665325: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 670ms/step - loss: 368.2272 - accuracy: 0.9758 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 11/20


2023-12-02 22:03:17.315040: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:03:18.055541: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 42.8146 - accuracy: 0.9844   

2023-12-02 22:03:18.724648: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 715.3450 - accuracy: 0.9688

2023-12-02 22:03:19.395166: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 640.6165 - accuracy: 0.9688

2023-12-02 22:03:20.069631: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 12s - loss: 691.6310 - accuracy: 0.9688

2023-12-02 22:03:20.738955: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 577.1208 - accuracy: 0.9688

2023-12-02 22:03:21.410934: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 620.9554 - accuracy: 0.9643

2023-12-02 22:03:22.079375: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 720.5863 - accuracy: 0.9609

2023-12-02 22:03:22.747519: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 651.9246 - accuracy: 0.9583

2023-12-02 22:03:23.418476: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 840.2046 - accuracy: 0.9500 

2023-12-02 22:03:24.084540: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 953.6319 - accuracy: 0.9432

2023-12-02 22:03:24.752927: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 1113.6196 - accuracy: 0.9427

2023-12-02 22:03:25.418745: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 1168.2689 - accuracy: 0.9399

2023-12-02 22:03:26.113962: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 2656.3667 - accuracy: 0.9241

2023-12-02 22:03:26.779685: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 3101.5796 - accuracy: 0.9167

2023-12-02 22:03:27.450377: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 3015.3999 - accuracy: 0.9160

2023-12-02 22:03:28.120719: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 2838.0234 - accuracy: 0.9210

2023-12-02 22:03:28.799786: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 2812.8271 - accuracy: 0.9219

2023-12-02 22:03:29.451179: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 2664.7837 - accuracy: 0.9260

2023-12-02 22:03:30.117158: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 2531.5444 - accuracy: 0.9297

2023-12-02 22:03:30.781071: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 2410.9949 - accuracy: 0.9330

2023-12-02 22:03:31.449282: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 2301.4041 - accuracy: 0.9361

2023-12-02 22:03:32.113979: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 2257.3110 - accuracy: 0.9375

2023-12-02 22:03:32.787687: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 670ms/step - loss: 2233.0391 - accuracy: 0.9382 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 12/20


2023-12-02 22:03:33.464807: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 2084.4272 - accuracy: 0.9375

2023-12-02 22:03:34.182609: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 1042.2136 - accuracy: 0.9688

2023-12-02 22:03:34.846442: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 13s - loss: 694.8091 - accuracy: 0.9792 

2023-12-02 22:03:35.511455: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 521.1068 - accuracy: 0.9844

2023-12-02 22:03:36.179079: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 12s - loss: 776.0656 - accuracy: 0.9812

2023-12-02 22:03:36.846434: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 769.1766 - accuracy: 0.9740

2023-12-02 22:03:37.519154: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 702.0746 - accuracy: 0.9732

2023-12-02 22:03:38.187191: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 808.8198 - accuracy: 0.9727

2023-12-02 22:03:38.857711: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 718.9509 - accuracy: 0.9757

2023-12-02 22:03:39.525823: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 698.7502 - accuracy: 0.9750 

2023-12-02 22:03:40.191447: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 635.2275 - accuracy: 0.9773

2023-12-02 22:03:40.860701: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 582.2918 - accuracy: 0.9792

2023-12-02 22:03:41.526586: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 537.5001 - accuracy: 0.9808

2023-12-02 22:03:42.198183: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 499.1073 - accuracy: 0.9821

2023-12-02 22:03:42.864308: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 465.8335 - accuracy: 0.9833

2023-12-02 22:03:43.528729: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 479.1845 - accuracy: 0.9824

2023-12-02 22:03:44.194616: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 450.9972 - accuracy: 0.9835

2023-12-02 22:03:44.859491: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 425.9418 - accuracy: 0.9844

2023-12-02 22:03:45.525545: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 403.5238 - accuracy: 0.9852

2023-12-02 22:03:46.195189: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 445.1528 - accuracy: 0.9844

2023-12-02 22:03:46.862043: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 476.9341 - accuracy: 0.9836

2023-12-02 22:03:47.524183: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 455.2553 - accuracy: 0.9844

2023-12-02 22:03:48.188394: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 438.6190 - accuracy: 0.9837

2023-12-02 22:03:48.851216: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 665ms/step - loss: 433.9026 - accuracy: 0.9839 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 13/20


2023-12-02 22:03:49.477546: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 482.7405 - accuracy: 0.9688

2023-12-02 22:03:50.188257: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 318.4379 - accuracy: 0.9531

2023-12-02 22:03:50.853397: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 613.0909 - accuracy: 0.9479

2023-12-02 22:03:51.523110: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 1167.8203 - accuracy: 0.9375

2023-12-02 22:03:52.194871: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 12s - loss: 964.2330 - accuracy: 0.9438 

2023-12-02 22:03:52.858310: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 992.5866 - accuracy: 0.9427

2023-12-02 22:03:53.529338: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 850.7885 - accuracy: 0.9509

2023-12-02 22:03:54.197472: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 780.1483 - accuracy: 0.9531

2023-12-02 22:03:54.871867: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 693.7022 - accuracy: 0.9549

2023-12-02 22:03:55.537723: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 627.7406 - accuracy: 0.9563 

2023-12-02 22:03:56.216462: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 570.6733 - accuracy: 0.9602

2023-12-02 22:03:56.878979: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 546.4326 - accuracy: 0.9583

2023-12-02 22:03:57.546890: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 591.8320 - accuracy: 0.9543

2023-12-02 22:03:58.213802: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 569.3321 - accuracy: 0.9554

2023-12-02 22:03:58.880994: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 531.3766 - accuracy: 0.9583

2023-12-02 22:03:59.547122: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 498.1656 - accuracy: 0.9609

2023-12-02 22:04:00.221943: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 503.1726 - accuracy: 0.9614

2023-12-02 22:04:00.888084: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 475.2186 - accuracy: 0.9635

2023-12-02 22:04:01.554640: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 450.2071 - accuracy: 0.9655

2023-12-02 22:04:02.219687: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 427.6967 - accuracy: 0.9672

2023-12-02 22:04:02.887052: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 444.0905 - accuracy: 0.9673

2023-12-02 22:04:03.551234: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 434.4856 - accuracy: 0.9673

2023-12-02 22:04:04.218092: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 416.6638 - accuracy: 0.9674

2023-12-02 22:04:04.882818: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 666ms/step - loss: 412.1836 - accuracy: 0.9677 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 14/20


2023-12-02 22:04:05.503106: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:04:06.212646: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:04:06.876779: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 13s - loss: 233.1601 - accuracy: 0.9792  

2023-12-02 22:04:07.543537: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 490.3750 - accuracy: 0.9766

2023-12-02 22:04:08.212048: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 12s - loss: 591.5377 - accuracy: 0.9750

2023-12-02 22:04:08.875702: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 11s - loss: 604.9289 - accuracy: 0.9688

2023-12-02 22:04:09.542968: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 779.1381 - accuracy: 0.9554

2023-12-02 22:04:10.212431: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 990.9899 - accuracy: 0.9531

2023-12-02 22:04:10.909669: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 958.5870 - accuracy: 0.9410

2023-12-02 22:04:11.575482: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 1127.0466 - accuracy: 0.9375

2023-12-02 22:04:12.242087: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 1024.5879 - accuracy: 0.9432

2023-12-02 22:04:12.916346: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 1043.1898 - accuracy: 0.9453

2023-12-02 22:04:13.586743: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 962.9445 - accuracy: 0.9495 

2023-12-02 22:04:14.256321: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 999.8288 - accuracy: 0.9487

2023-12-02 22:04:14.921882: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 933.1736 - accuracy: 0.9521

2023-12-02 22:04:15.581151: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 920.5154 - accuracy: 0.9531

2023-12-02 22:04:16.258904: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 912.9644 - accuracy: 0.9540

2023-12-02 22:04:16.924559: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 956.4551 - accuracy: 0.9514

2023-12-02 22:04:17.660606: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 922.3074 - accuracy: 0.9523

2023-12-02 22:04:18.511780: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 952.0895 - accuracy: 0.9516

2023-12-02 22:04:19.560808: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 906.7520 - accuracy: 0.9539

2023-12-02 22:04:20.294920: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 865.5359 - accuracy: 0.9560

2023-12-02 22:04:21.087851: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 827.9039 - accuracy: 0.9579

2023-12-02 22:04:21.761244: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 17s 705ms/step - loss: 819.0018 - accuracy: 0.9583 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 15/20


2023-12-02 22:04:22.433678: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:04:23.141394: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:04:23.809806: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 8.1980 - accuracy: 0.9896    

2023-12-02 22:04:24.483428: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 6.1485 - accuracy: 0.9922

2023-12-02 22:04:25.152931: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 12s - loss: 34.1501 - accuracy: 0.9875

2023-12-02 22:04:25.821194: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 508.7516 - accuracy: 0.9792

2023-12-02 22:04:26.493363: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 436.0728 - accuracy: 0.9821

2023-12-02 22:04:27.164075: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 381.5637 - accuracy: 0.9844

2023-12-02 22:04:27.837887: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 369.8303 - accuracy: 0.9826

2023-12-02 22:04:28.534332: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 332.8473 - accuracy: 0.9844 

2023-12-02 22:04:29.218331: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 302.5884 - accuracy: 0.9858

2023-12-02 22:04:29.888213: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 462.5459 - accuracy: 0.9844

2023-12-02 22:04:30.559167: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 443.4765 - accuracy: 0.9832

2023-12-02 22:04:31.228733: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 411.7996 - accuracy: 0.9844

2023-12-02 22:04:31.940039: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 391.0141 - accuracy: 0.9833

2023-12-02 22:04:32.657787: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 366.5757 - accuracy: 0.9844

2023-12-02 22:04:33.330832: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 457.3510 - accuracy: 0.9816

2023-12-02 22:04:34.021767: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 464.8273 - accuracy: 0.9792

2023-12-02 22:04:34.699116: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 440.3627 - accuracy: 0.9803

2023-12-02 22:04:35.386640: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 423.6607 - accuracy: 0.9797

2023-12-02 22:04:36.049831: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 897.1100 - accuracy: 0.9688

2023-12-02 22:04:36.757982: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 856.3323 - accuracy: 0.9702

2023-12-02 22:04:37.430576: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 869.2637 - accuracy: 0.9674

2023-12-02 22:04:38.097925: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 679ms/step - loss: 884.9388 - accuracy: 0.9664 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 16/20


2023-12-02 22:04:38.758901: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:04:39.478337: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 16s - loss: 66.5043 - accuracy: 0.9688   

2023-12-02 22:04:40.209283: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 76.1573 - accuracy: 0.9688

2023-12-02 22:04:40.877982: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 151.4935 - accuracy: 0.9688

2023-12-02 22:04:41.554131: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 13s - loss: 135.5988 - accuracy: 0.9688

2023-12-02 22:04:42.226362: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 112.9990 - accuracy: 0.9740

2023-12-02 22:04:42.909481: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 96.8563 - accuracy: 0.9777 

2023-12-02 22:04:43.578895: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 84.7493 - accuracy: 0.9805

2023-12-02 22:04:44.247098: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 75.3327 - accuracy: 0.9826

2023-12-02 22:04:44.915384: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 67.7994 - accuracy: 0.9844 

2023-12-02 22:04:45.585323: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 61.6358 - accuracy: 0.9858

2023-12-02 22:04:46.258925: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 56.4995 - accuracy: 0.9870

2023-12-02 22:04:46.932145: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 52.1534 - accuracy: 0.9880

2023-12-02 22:04:47.602996: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 48.4282 - accuracy: 0.9888

2023-12-02 22:04:48.271729: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 45.1996 - accuracy: 0.9896

2023-12-02 22:04:48.938702: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 42.3746 - accuracy: 0.9902

2023-12-02 22:04:49.604965: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 39.8820 - accuracy: 0.9908

2023-12-02 22:04:50.272512: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 37.6663 - accuracy: 0.9913

2023-12-02 22:04:50.939736: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 35.6839 - accuracy: 0.9918

2023-12-02 22:04:51.607633: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 33.8997 - accuracy: 0.9922

2023-12-02 22:04:52.276109: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 49.3978 - accuracy: 0.9911

2023-12-02 22:04:52.943515: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 211.9672 - accuracy: 0.9858

2023-12-02 22:04:53.617608: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 202.7513 - accuracy: 0.9864

2023-12-02 22:04:54.285405: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 671ms/step - loss: 200.5712 - accuracy: 0.9866 - val_loss: 2939.0955 - val_accuracy: 0.9333
Epoch 17/20


2023-12-02 22:04:54.906336: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 364.7455 - accuracy: 0.9375

2023-12-02 22:04:55.627873: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 182.3728 - accuracy: 0.9688

2023-12-02 22:04:56.298340: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 121.5818 - accuracy: 0.9792

2023-12-02 22:04:56.969150: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 91.1864 - accuracy: 0.9844 

2023-12-02 22:04:57.637768: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 12s - loss: 72.9491 - accuracy: 0.9875

2023-12-02 22:04:58.308483: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 60.7909 - accuracy: 0.9896

2023-12-02 22:04:58.979342: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 52.1065 - accuracy: 0.9911

2023-12-02 22:04:59.648872: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 59.9933 - accuracy: 0.9883

2023-12-02 22:05:00.318359: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 53.3274 - accuracy: 0.9896

2023-12-02 22:05:00.988299: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 179.2200 - accuracy: 0.9844

2023-12-02 22:05:01.657560: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 286.4020 - accuracy: 0.9773

2023-12-02 22:05:02.327779: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 262.5352 - accuracy: 0.9792

2023-12-02 22:05:02.998277: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 450.1971 - accuracy: 0.9784

2023-12-02 22:05:03.668959: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 440.9748 - accuracy: 0.9777

2023-12-02 22:05:04.335167: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 411.5765 - accuracy: 0.9792

2023-12-02 22:05:05.004591: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 385.8530 - accuracy: 0.9805

2023-12-02 22:05:05.670094: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 363.1557 - accuracy: 0.9816

2023-12-02 22:05:06.338321: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 342.9804 - accuracy: 0.9826

2023-12-02 22:05:07.004237: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 332.3457 - accuracy: 0.9819

2023-12-02 22:05:07.675854: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 384.7906 - accuracy: 0.9797

2023-12-02 22:05:08.343771: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 457.3091 - accuracy: 0.9762

2023-12-02 22:05:09.010132: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 437.4860 - accuracy: 0.9759

2023-12-02 22:05:09.688819: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 504.0017 - accuracy: 0.9755

2023-12-02 22:05:10.359254: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 667ms/step - loss: 498.5824 - accuracy: 0.9758 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 18/20


2023-12-02 22:05:10.965503: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 0.0000e+00 - accuracy: 1.0000

2023-12-02 22:05:11.691158: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 887.4634 - accuracy: 0.9688  

2023-12-02 22:05:12.368939: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 591.6423 - accuracy: 0.9792

2023-12-02 22:05:13.041955: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 443.7317 - accuracy: 0.9844

2023-12-02 22:05:13.728893: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 12s - loss: 354.9854 - accuracy: 0.9875

2023-12-02 22:05:14.395681: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 347.4921 - accuracy: 0.9844

2023-12-02 22:05:15.069800: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 315.5979 - accuracy: 0.9821

2023-12-02 22:05:15.749224: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 294.2051 - accuracy: 0.9805

2023-12-02 22:05:16.420207: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 261.5156 - accuracy: 0.9826

2023-12-02 22:05:17.089386: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 235.3641 - accuracy: 0.9844 

2023-12-02 22:05:17.759570: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 224.3114 - accuracy: 0.9830

2023-12-02 22:05:18.427686: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 329.5728 - accuracy: 0.9792

2023-12-02 22:05:19.098085: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 370.9053 - accuracy: 0.9784

2023-12-02 22:05:19.767403: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 344.4121 - accuracy: 0.9799

2023-12-02 22:05:20.435929: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 321.4513 - accuracy: 0.9812

2023-12-02 22:05:21.102046: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 422.9140 - accuracy: 0.9785

2023-12-02 22:05:21.768958: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 549.8220 - accuracy: 0.9743

2023-12-02 22:05:22.437306: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 519.2764 - accuracy: 0.9757

2023-12-02 22:05:23.104791: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 491.9460 - accuracy: 0.9770

2023-12-02 22:05:23.787328: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 467.3487 - accuracy: 0.9781

2023-12-02 22:05:24.436758: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 445.0940 - accuracy: 0.9792

2023-12-02 22:05:25.104917: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 471.5347 - accuracy: 0.9787

2023-12-02 22:05:25.774615: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 518.2978 - accuracy: 0.9769

2023-12-02 22:05:26.466573: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 669ms/step - loss: 512.7247 - accuracy: 0.9772 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 19/20


2023-12-02 22:05:27.078976: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 16s - loss: 262.3413 - accuracy: 0.9375

2023-12-02 22:05:27.790948: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 14s - loss: 131.1706 - accuracy: 0.9688

2023-12-02 22:05:28.458612: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 14s - loss: 182.9930 - accuracy: 0.9688

2023-12-02 22:05:29.127680: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 13s - loss: 283.0621 - accuracy: 0.9609

2023-12-02 22:05:29.795522: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 12s - loss: 366.7250 - accuracy: 0.9625

2023-12-02 22:05:30.463470: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 12s - loss: 305.6042 - accuracy: 0.9688

2023-12-02 22:05:31.134410: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 11s - loss: 261.9464 - accuracy: 0.9732

2023-12-02 22:05:31.805187: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 10s - loss: 229.2031 - accuracy: 0.9766

2023-12-02 22:05:32.474337: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 10s - loss: 203.7361 - accuracy: 0.9792

2023-12-02 22:05:33.144664: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 9s - loss: 183.3625 - accuracy: 0.9812 

2023-12-02 22:05:33.815139: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 8s - loss: 166.6932 - accuracy: 0.9830

2023-12-02 22:05:34.486779: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 261.8779 - accuracy: 0.9818

2023-12-02 22:05:35.156086: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 7s - loss: 253.9445 - accuracy: 0.9808

2023-12-02 22:05:35.824121: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 6s - loss: 394.5921 - accuracy: 0.9754

2023-12-02 22:05:36.497852: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 368.2860 - accuracy: 0.9771

2023-12-02 22:05:37.175168: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 345.2681 - accuracy: 0.9785

2023-12-02 22:05:37.866734: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 406.6888 - accuracy: 0.9761

2023-12-02 22:05:38.547751: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 410.4196 - accuracy: 0.9757

2023-12-02 22:05:39.216929: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 388.8185 - accuracy: 0.9770

2023-12-02 22:05:39.886235: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 369.3776 - accuracy: 0.9781

2023-12-02 22:05:40.552914: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 351.7882 - accuracy: 0.9792

2023-12-02 22:05:41.221028: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 335.7978 - accuracy: 0.9801

2023-12-02 22:05:41.888464: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 331.1212 - accuracy: 0.9796

2023-12-02 22:05:42.553869: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 16s 671ms/step - loss: 327.5608 - accuracy: 0.9798 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 20/20


2023-12-02 22:05:43.220254: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 1/24 [>.............................] - ETA: 17s - loss: 1290.8525 - accuracy: 0.9688

2023-12-02 22:05:44.001755: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 2/24 [=>............................] - ETA: 17s - loss: 719.0704 - accuracy: 0.9688 

2023-12-02 22:05:44.800613: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 3/24 [==>...........................] - ETA: 15s - loss: 703.9025 - accuracy: 0.9583

2023-12-02 22:05:45.510481: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 4/24 [====>.........................] - ETA: 15s - loss: 546.8181 - accuracy: 0.9609

2023-12-02 22:05:46.256408: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 5/24 [=====>........................] - ETA: 14s - loss: 437.4544 - accuracy: 0.9688

2023-12-02 22:05:46.999702: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 6/24 [======>.......................] - ETA: 13s - loss: 402.3908 - accuracy: 0.9635

2023-12-02 22:05:47.768266: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 7/24 [=======>......................] - ETA: 12s - loss: 928.3969 - accuracy: 0.9554

2023-12-02 22:05:48.454957: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 8/24 [=========>....................] - ETA: 11s - loss: 1232.6022 - accuracy: 0.9492

2023-12-02 22:05:49.139764: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


 9/24 [==========>...................] - ETA: 11s - loss: 1345.8939 - accuracy: 0.9444

2023-12-02 22:05:49.875213: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


10/24 [===========>..................] - ETA: 10s - loss: 1211.3044 - accuracy: 0.9500

2023-12-02 22:05:50.572339: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


11/24 [============>.................] - ETA: 9s - loss: 1191.9269 - accuracy: 0.9460 

2023-12-02 22:05:51.315482: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


12/24 [==============>...............] - ETA: 8s - loss: 1092.5996 - accuracy: 0.9505

2023-12-02 22:05:52.054324: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


13/24 [===============>..............] - ETA: 8s - loss: 1008.5535 - accuracy: 0.9543

2023-12-02 22:05:52.749145: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


14/24 [================>.............] - ETA: 7s - loss: 1253.0862 - accuracy: 0.9531

2023-12-02 22:05:53.417153: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


15/24 [=================>............] - ETA: 6s - loss: 1372.9902 - accuracy: 0.9458

2023-12-02 22:05:54.085981: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


16/24 [===================>..........] - ETA: 5s - loss: 1287.1783 - accuracy: 0.9492

2023-12-02 22:05:54.754155: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


17/24 [====================>.........] - ETA: 4s - loss: 1255.1766 - accuracy: 0.9485

2023-12-02 22:05:55.420505: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


18/24 [=====================>........] - ETA: 4s - loss: 1187.8412 - accuracy: 0.9497

2023-12-02 22:05:56.086473: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


19/24 [======================>.......] - ETA: 3s - loss: 1133.3314 - accuracy: 0.9507

2023-12-02 22:05:56.752916: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


20/24 [========================>.....] - ETA: 2s - loss: 1110.1938 - accuracy: 0.9516

2023-12-02 22:05:57.419314: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


21/24 [=========================>....] - ETA: 2s - loss: 1498.8750 - accuracy: 0.9420

2023-12-02 22:05:58.087782: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


22/24 [==========================>...] - ETA: 1s - loss: 1699.2477 - accuracy: 0.9418

2023-12-02 22:05:58.756537: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


23/24 [===========================>..] - ETA: 0s - loss: 1625.3673 - accuracy: 0.9443

2023-12-02 22:05:59.421967: I metal_plugin/src/kernels/stateless_random_op.cc:282] Note the GPU implementation does not produce the same series as CPU implementation.


24/24 [==============================] - 17s 698ms/step - loss: 1607.8903 - accuracy: 0.9449 - val_loss: 0.0000e+00 - val_accuracy: 1.0000


In [184]:
test_model = keras.models.load_model(
    "./models/vgg16_bird_classifier.tf")
test_loss, test_acc = test_model.evaluate(test_dataset)

# we need to change the encoding of the labels to feed into confusion matrix
def change_encoding(labels):
    output = []
    for row in labels:
        # the argmax would be the corresponding class
        label = np.argmax(row)
        output.append(label)
    return output

conf_mat_lst = []
precision_lst = []
recall_lst = []
roc_auc_lst = []
for i in range(0, 10):
    pred_vals = change_encoding(test_model.predict(test_dataset))

    # confusion matrix is in the form:
    #  actual\predicted  0     1     2
    #            0       
    #            1       
    #            2       
    # where the row labels are (actual) and column labels are (predicted)
    conf_mat = confusion_matrix(test_labels, pred_vals)

    # I chose 'macro' as it
    precision_macro = precision_score(test_labels, pred_vals, average= 'macro')
    recall_macro = recall_score(test_labels, pred_vals, average= 'macro')

    # the roc_auc_score requires the probability for each class, so we feed in the 
    # raw model.predict results instead of my converted ones
    # multi_class = 'ovr' as our classes are relatively balanced
    roc_auc = roc_auc_score(test_labels, test_model.predict(test_dataset), multi_class= 'ovr')

    conf_mat_lst.append(conf_mat)
    precision_lst.append(precision_macro)
    recall_lst.append(recall_macro)
    roc_auc_lst.append(roc_auc)

1/1 [==============================] - 0s 14ms/step


In [186]:
print(np.mean(precision_lst))
print(np.mean(recall_lst))
print(np.mean(roc_auc_lst))
print(conf_mat_lst)

0.37333333333333335
0.37333333333333335
0.44499999999999995
[array([[1, 3, 1],
       [2, 1, 2],
       [2, 1, 2]]), array([[2, 1, 2],
       [3, 0, 2],
       [0, 4, 1]]), array([[2, 2, 1],
       [1, 2, 2],
       [2, 1, 2]]), array([[3, 1, 1],
       [2, 2, 1],
       [0, 2, 3]]), array([[2, 2, 1],
       [2, 1, 2],
       [1, 2, 2]]), array([[1, 2, 2],
       [1, 2, 2],
       [3, 1, 1]]), array([[2, 2, 1],
       [2, 2, 1],
       [1, 1, 3]]), array([[2, 2, 1],
       [3, 1, 1],
       [0, 2, 3]]), array([[2, 2, 1],
       [2, 1, 2],
       [1, 2, 2]]), array([[3, 0, 2],
       [1, 3, 1],
       [1, 2, 2]])]


Note: Our model seems to behave non-deterministicly. I'm not entirely sure why that is at the moment, as the non-deterministic element (the dropout layer) should be disabled when running the model.predict() line. As such, I have decided to run the prediction 10 times, and get the mean performance metric value.

Our model does not perform very well at classifying these birds at the moment. Both precision and recall are very low, and the AUC value is lower than 0.5. This indicates that our model performs worse than random chance.

This can also be seen by the precision and recall values. They are both quite low at around 0.37. This indicates that it does not distinguish between the different species of birds very well.

Looking at the confusion matrix, there seems to be a relatively even number of errors across the matrix. However, it is only 15 photographs in the test set, which is a very limited set. As such, small deviations in performance would have a great impact on our metrics given that a lot of them are proportional. As such, a larger test set would more adequately demonstrate the model's performance.